# .github/workflows/sync.yml
name: Rebase Upstream
on:
  schedule:
  - cron: "0 0 * * 0"  # run once a week
  workflow_dispatch:    # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2  # greater than the number of commits you made
    - uses: imba-tjd/rebase-upstream-action@0.5
      with:
        upstream: qmk/qmk_firmware
        branch:   master
